name: Generate `snk` Animation

on:
  schedule:
    # every 6 hours
    - cron: "0 */6 * * *"

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@master
        with:
          github_user_name: danielfalbo
          svg_out_path: snk.svg
